name: Sync Fork with Upstream # 워크플로우 이름

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정(UTC)에 자동으로 실행
  workflow_dispatch: # GitHub Actions 탭에서 수동으로 실행 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. 개인 레포지토리(Fork)를 Checkout
      # - Personal Access Token(PAT)을 사용해야 원격 저장소에 push 할 수 있습니다.
      # - 각자 자신의 포크된 레포지토리의 [Settings] > [Secrets]에 PAT를 등록해야 합니다.
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 모든 커밋 히스토리를 가져옵니다.
          token: ${{ secrets.PAT }} # GitHub Secrets에 등록된 PAT를 사용합니다.

      # 2. Git 사용자 정보 설정
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 3. 팀의 원본(Upstream) 저장소를 원격 저장소로 추가
      # - 'upstream'이라는 이름으로 원본 저장소를 등록합니다.
      - name: Add upstream remote
        run: |
          git remote get-url upstream || git remote add upstream https://github.com/OZ-Coding-School/oz_externship_fe_01_team3

      # 4. 원본 저장소의 최신 변경사항을 가져옴
      - name: Fetch upstream changes
        run: git fetch upstream

      # 5. 개인 레포의 develop 브랜치를 원본의 develop 브랜치와 강제로 동기화
      # - 주의: 이 과정은 개인 레포의 develop 브랜치에만 있던 커밋을 모두 삭제합니다.
      # - 항상 작업은 별도의 피쳐(feature) 브랜치에서 진행해야 합니다.
      - name: Reset develop branch to upstream/develop
        run: |
          git checkout develop
          git reset --hard upstream/develop
          git push origin develop --force
